name: fast_recipe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  image: ^4.2.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/models/
